#!/usr/bin/env python3
"""il centro di italia — Day 1. Data only (R-IC1). Same shape as day2_data.py."""

CHAPTERS = [
    ("chapter-1", 'Nomi, genere e numero', [
        ('ex-01', 'la regola / le regole', 'la regola, le regole', 'the rule, the rules',
         ''),
        ('ex-02', "l'attore / l'attrice", "l'attore, l'attrice", 'the actor, the actress',
         ''),
        ('ex-12', 'i registi / le registe', 'i registi, le registe', 'the directors, the women directors',
         ''),
        ('ex-13', 'gli attori / le attrici', 'gli attori, le attrici', 'the actors, the actresses',
         ''),
        ('ex-14', 'i fenomeni', 'i fenomeni', 'the phenomena',
         ''),
        ('ex-15', 'i rischi', 'i rischi', 'the risks',
         ''),
        ('ex-16', 'i consigli', 'i consigli', 'the pieces of advice',
         ''),
        ('ex-20', 'un attore', 'un attore', 'an actor',
         ''),
        ('ex-04', 'devo studiare più italiano', 'devo studiare più italiano', 'I have to study more Italian',
         ''),
        ('ex-05', 'mi piace più guardare', 'mi piace più guardare', 'I prefer watching',
         ''),
    ]),
    ("chapter-2", 'Conversazione quotidiana', [
        ('classe-01', 'Da quanto tempo abiti in Italia?', 'Da quanto tempo abiti in Italia?', 'How long have you been living in Italy?',
         'da + PRESENT tense — Italian says \\"abito da tre anni\\", not a past tense.'),
        ('classe-02', 'Hai tempo per scrivere una presentazione?', 'Hai tempo per scrivere una presentazione?', 'Do you have time to write a presentation?',
         'avere tempo; per + infinito = \\"to / in order to\\".'),
        ('classe-03', 'Voglio praticare la pronuncia.', 'Voglio praticare la pronuncia.', 'I want to practise pronunciation.',
         'volere + infinito, no preposition between them.'),
        ('classe-04', 'domandare', 'domandare', 'to ask (a question)',
         'chiedere covers asking a question AND asking for something; fare una domanda is the everyday phrase.'),
        ('classe-05', 'un consiglio', 'un consiglio', 'a piece of advice, a tip',
         'Countable in Italian: i consigli. dare un consiglio = to give advice.'),
        ('classe-08', 'Ci vediamo domani alla stessa ora, allo stesso posto.', 'Ci vediamo domani alla stessa ora, allo stesso posto.', 'See you tomorrow, same time, same place.',
         'ci vediamo = we see each other. a+la=alla, a+lo=allo.'),
        ('ex-07', 'abito qui da tre anni', 'abito qui da tre anni', "I've been living here for three years",
         ''),
        ('ex-08', 'fare una domanda', 'fare una domanda', 'to ask a question',
         ''),
    ]),
    ("chapter-3", "L'ora", [
        ('tempo-01', 'Adesso sono le 4.36 di mattina.', 'Adesso sono le quattro e trentasei di mattina.', "It's 4:36 in the morning now.",
         'sono le + number for every hour except 1, noon and midnight.'),
        ('tempo-02', 'Qui sono le 15.00 di pomeriggio.', 'Qui sono le quindici, le tre di pomeriggio.', "Here it's 3 in the afternoon.",
         'di mattina / di pomeriggio / di sera / di notte.'),
        ('tempo-03', 'La prima riunione comincia alle 9.00.', 'La prima riunione comincia alle nove.', 'The first meeting starts at 9:00.',
         'cominciare alle + hour.'),
        ('tempo-04', 'Ho molte riunioni di lavoro.', 'Ho molte riunioni di lavoro.', 'I have a lot of work meetings.',
         'NOTE: di lavoro stays SINGULAR in this fixed phrase (the log shows \\"di lavori\\" — that means roadworks).'),
        ('dt-01', 'Sono le quattro.', 'Sono le quattro.', "It's four o'clock",
         ''),
        ('dt-02', "È l'una. / È mezzogiorno. / È mezzanotte.", "È l'una. È mezzogiorno. È mezzanotte.", "It's one o'clock. It's noon. It's midnight",
         ''),
        ('ex-09', 'È mezzogiorno. / È mezzanotte.', 'È mezzogiorno. È mezzanotte.', "it's noon, it's midnight",
         ''),
        ('ex-10', 'di mattina · di pomeriggio · di sera · di notte', 'di mattina, di pomeriggio, di sera, di notte', 'in the morning, in the afternoon, in the evening, at night',
         ''),
        ('ex-11', 'alle 9.00 · alle 9.55 · alla stessa ora', 'alle nove, alle nove e cinquantacinque, alla stessa ora', 'at nine, at nine fifty-five, at the same time',
         ''),
        ('classe-09', 'alle 9.55', 'alle nove e cinquantacinque', 'at 9:55',
         '\\"At\\" a time = alle. Italian writes times with a period, not a colon.'),
        ('ex-17', 'lavori in corso', 'lavori in corso', 'roadworks in progress',
         ''),
        ('ex-18', 'orario di lavoro', 'orario di lavoro', 'working hours',
         ''),
    ]),
    ("chapter-4", 'Grammatica', [
        ('gram-01', 'La gente è pazza.', 'La gente è pazza.', 'People are crazy.',
         'la gente is grammatically SINGULAR — è, never sono. Use le persone for a real plural.'),
        ('gram-02', 'La gente a Nord viaggia a Sud.', 'La gente a Nord viaggia a Sud.', 'People in the North travel to the South.',
         'Singular verb again: viaggia, not viaggiano.'),
        ('gram-03', 'La gente era ottimista.', 'La gente era ottimista.', 'People were optimistic.',
         'Imperfetto era = was / used to be. Still singular agreement.'),
        ('gram-04', "Non c'è una regola.", "Non c'è una regola.", "There's no rule.",
         "c'è + singular, ci sono + plural."),
        ('gram-06', 'Devo studiare più italiano.', 'Devo studiare più italiano.', 'I have to study more Italian.',
         'Her shorthand was \\"studiare + italiano\\" — the + means più. dovere + infinito.'),
        ('gram-07', 'Lei non ha pazienza.', 'Lei non ha pazienza.', 'She has no patience.',
         'avere pazienza — you HAVE the state. Same family: avere fame, sete, sonno, ragione, paura.'),
        ('gram-08', 'Lui si innamora di Sofia Loren.', 'Lui si innamora di Sofia Loren.', 'He falls in love with Sofia Loren.',
         'innamorarsi DI, never con.'),
        ('gram-09', 'Mi piace guardare il cinema italiano.', 'Mi piace guardare il cinema italiano.', 'I like watching Italian cinema.',
         'mi piace + infinito. Plural things take mi piacciono.'),
        ('gram-10', 'fare il bagno', 'fare il bagno', 'to take a dip, to go for a swim',
         'Uses fare. nuotare = to swim as an activity/sport.'),
        ('dt-03', 'nel fiume · nel lago', 'nel fiume, nel lago', 'in the river, in the lake',
         ''),
        ('gram-13', 'nella fontana', 'nella fontana', 'in the fountain',
         'in + la = nella. la fontana.'),
        ('gram-14', "la vita degli anni '60", 'la vita degli anni sessanta', "life in the '60s",
         'di + gli = degli.'),
        ('gram-15', 'la generazione di mia moglie', 'la generazione di mia moglie', "my wife's generation",
         'NO article before a singular unmodified family member: mia moglie, not la mia moglie.'),
        ('gram-16', "un'attrice internazionale", "un'attrice internazionale", 'an international actress',
         "un' with apostrophe only before a FEMININE vowel-initial noun. Masculine is un attore, no apostrophe."),
        ('ex-06', 'le persone sono pazze', 'le persone sono pazze', 'people are crazy',
         ''),
        ('ex-19', 'avere fame, sete, sonno, ragione, paura', 'avere fame, avere sete, avere sonno, avere ragione, avere paura', 'to be hungry, thirsty, sleepy, right, afraid',
         ''),
    ]),
    ("chapter-5", 'Il turismo', [
        ('tur-01', "Il turismo è importante per l'Italia.", "Il turismo è importante per l'Italia.", 'Tourism is important for Italy.',
         ''),
        ('tur-02', 'un fenomeno italiano', 'un fenomeno italiano', 'an Italian phenomenon',
         'il fenomeno → i fenomeni.'),
        ('tur-03', 'il turismo selvaggio', 'il turismo selvaggio', 'unchecked / \\"wild\\" mass tourism',
         'selvaggio = wild, savage, unregulated. A loaded phrase in current Italian debate.'),
        ('tur-04', 'Ferragosto', 'Ferragosto', "15 August — Italy's peak national holiday",
         'The country empties out and heads for the coast; explains the whole August exodus.'),
        ('dt-04', 'il governo · il rischio', 'il governo, il rischio', 'the government, the risk',
         ''),
        ('tur-07', 'Fare il bagno nella fontana di Trevi', 'Fare il bagno nella fontana di Trevi.', 'To bathe in the Trevi Fountain',
         'The notorious tourist offence — it carries a fine.'),
        ('tur-08', 'a Nord / a Sud', 'a Nord, a Sud', 'in the North / to the South',
         'Also al Nord / al Sud.'),
    ]),
    ("chapter-6", 'Il cinema', [
        ('cin-01', 'in bianco e nero', 'in bianco e nero', 'in black and white',
         'No article.'),
        ('cin-02', 'il regista', 'il regista', 'the film director',
         'FALSE FRIEND — not \\"registrar\\". Masculine despite the -a: il regista → i registi; la regista → le registe.'),
        ('cin-03', "l'attore / l'attrice", "l'attore, l'attrice", 'the actor / the actress',
         'Plural: gli attori / le attrici.'),
        ('dt-05', 'Il Sorpasso — 1962', 'Il Sorpasso, millenovecentosessantadue', 'Il Sorpasso, nineteen sixty-two',
         ''),
        ('cin-05', 'Dino Risi', 'Dino Risi', 'the director of Il Sorpasso',
         'Her note \\"Dino Risi &lt; il regista\\" = \\"who is the director\\".'),
        ('cin-06', 'Vittorio Gassman', 'Vittorio Gassman', 'the lead actor of Il Sorpasso',
         ''),
        ('dt-06', "la vita degli anni '60, il boom economico", 'la vita degli anni sessanta, il boom economico', 'life in the sixties, the economic boom',
         ''),
        ('cin-09', 'il film cult della Dolce Vita', 'il film cult della Dolce Vita', 'the cult film La Dolce Vita',
         'Fellini, 1960 — the Trevi Fountain scene. il film is invariable: i film.'),
        ('cin-10', 'Ieri, Oggi, Domani', 'Ieri, Oggi, Domani', '\\"Yesterday, Today, Tomorrow\\" (1963)',
         'De Sica, with Sofia Loren and Marcello Mastroianni.'),
    ]),
    ("chapter-7", 'Pratica', [
        ('sca-01', 'Abito in Italia da tre anni.', 'Abito in Italia da tre anni.', "I've been living in Italy for three years",
         ''),
        ('sca-02', 'Ogni giorno ho molte riunioni di lavoro.', 'Ogni giorno ho molte riunioni di lavoro.', 'Every day I have a lot of work meetings',
         ''),
        ('sca-03', 'Devo studiare più italiano perché voglio parlare bene.', 'Devo studiare più italiano perché voglio parlare bene.', 'I have to study more Italian because I want to speak well',
         ''),
        ('sca-04', 'Mi piace guardare il cinema italiano in bianco e nero.', 'Mi piace guardare il cinema italiano in bianco e nero.', 'I like watching Italian cinema in black and white',
         ''),
        ('sca-05', 'Il mio film preferito è Il Sorpasso, del regista Dino Risi.', 'Il mio film preferito è Il Sorpasso, del regista Dino Risi.', 'My favourite film is Il Sorpasso, by the director Dino Risi',
         ''),
        ('classe-06', 'una presentazione al presente', 'una presentazione al presente', 'a presentation in the present tense',
         'Your homework: topic = la mia vita in Italia.'),
        ('classe-07', 'la mia vita in Italia', 'la mia vita in Italia', 'my life in Italy',
         'The homework topic she assigned.'),
    ]),
]

PEARLS = {
    "chapter-3": ("pearl-di-lavoro",
        "<strong>riunioni di lavoro</strong>, non <em>di lavori</em>. In questa espressione fissa "
        "<strong>lavoro</strong> resta singolare e invariabile, come in <em>orario di lavoro</em>. "
        "<em>Lavori</em> al plurale significa i lavori stradali.",
        "Say riunioni di lavoro, not di lavori. In this fixed compound lavoro stays singular and "
        "invariable. The plural lavori means roadworks."),
    "chapter-4": ("pearl-la-gente",
        "<strong>La gente</strong> \u00e8 un nome collettivo <strong>singolare</strong>: "
        "<em>la gente \u00e8 pazza</em>, <em>la gente viaggia</em>. Mai <em>sono</em>. "
        "Per un vero plurale si usa <strong>le persone</strong>.",
        "La gente is a singular collective noun. English 'people' is plural and will fight you. "
        "For a true plural use le persone."),
    "chapter-6": ("pearl-il-regista",
        "<strong>Il regista</strong> finisce in <em>-a</em> ma \u00e8 <strong>maschile</strong>: "
        "<em>il regista, i registi</em>. Al femminile: <em>la regista, le registe</em>.",
        "Il regista ends in -a but is masculine. Feminine is la regista, le registe. "
        "It is not a 'registrar'."),
}

TRAP = ("ho molte riunioni di <s>lavori</s> lavoro",
        "Il transcript scrive <em>di lavori</em>. La forma giusta \u00e8 <strong>di lavoro</strong>, "
        "singolare e invariabile in questa espressione fissa.",
        "The transcript shows di lavori. The correct form is di lavoro - singular and invariable "
        "in this fixed phrase. Lavori means roadworks.")

RECAP = []   # Day 1 opens the series

CLOZE = [
    ("\u00e8", "La gente ___ pazza.", "singolare!"),
    ("lavoro", "Ho molte riunioni di ___.", "invariabile"),
    ("sono", "___ le quattro di mattina.", "plurale"),
    ("alle", "La prima riunione comincia ___ nove.", "a + le"),
    ("nella", "Fare il bagno ___ fontana di Trevi.", "in + la"),
    ("mia", "La generazione di ___ moglie.", "niente articolo"),
]

COLD_OPEN_IT = "Qui sono le tre di pomeriggio; l\u00ec sono le quattro e trentasei di mattina."
COLD_OPEN_EN = "Here it's three in the afternoon; there it's four thirty-six in the morning."
